### Pandas

In [1]:
import pandas

# Reading csv
dataframe = pandas.read_csv("cancer.csv", header=1)

# Converting dataframe to list
dataframe.values.tolist()[:2]

[['M',
  20.57,
  17.77,
  132.9,
  1326.0,
  0.08474,
  0.07864,
  0.0869,
  0.07017000000000001,
  0.1812,
  0.056670000000000005,
  0.5435,
  0.7339,
  3.398,
  74.08,
  0.005225,
  0.013080000000000001,
  0.0186,
  0.0134,
  0.013890000000000001,
  0.003532,
  24.99,
  23.41,
  158.8,
  1956.0,
  0.1238,
  0.1866,
  0.2416,
  0.18600000000000003,
  0.275,
  0.08902],
 ['M',
  19.69,
  21.25,
  130.0,
  1203.0,
  0.1096,
  0.1599,
  0.1974,
  0.1279,
  0.2069,
  0.059989999999999995,
  0.7456,
  0.7869,
  4.585,
  94.03,
  0.00615,
  0.040060000000000005,
  0.03832,
  0.02058,
  0.0225,
  0.004571,
  23.57,
  25.53,
  152.5,
  1709.0,
  0.1444,
  0.4245,
  0.4504,
  0.243,
  0.3613,
  0.08757999999999999]]

### NumPy

In [2]:
import numpy as np

# Converting from and to list
vector = [1, 2, 3]
np_vector = np.array(vector)
vector = np_vector.tolist()
matrix = [[1, 2, 3], [4, 5, 6]]
np_matrix = np.array(matrix)
matrix = np_matrix.tolist()

In [3]:
# Elementvise operations
np_vector * np_vector
np_vector - np_vector
np_vector + np_vector
np_vector / np_vector
np_matrix * np_vector
np_matrix - np_vector
np_matrix + np_vector
np_matrix / np_vector

# Tensor operations
np_vector.dot(np_vector) # Production
np_matrix.T # Transpose

# Other operations
np.unique(np_vector)
np.argmax(np_matrix, axis=1)
np.min(np_matrix, axis=0)

array([1, 2, 3])

In [4]:
# Primitives
ones = np.ones((4, 3, 2))
zeros = np.zeros((2, 3, 4))
np_range = np.arange(1, 6)
np_range = np.arange(1, 6, 0.5)
np_linspace = np.linspace(0, 1, 4)
eye = np.eye(4)

In [5]:
# Shape
a = np.linspace(0, 1, 12)
a = a.reshape((2, 6))
a = a.reshape((-1, 3))

In [6]:
# Random
normal_distribution = np.random.randn(2, 3)
uniform_distribution = np.random.random((2, 3))
integers = np.random.randint(1, 3, (2, 3))

In [7]:
# Slicing
normal_distribution = np.random.randn(6, 8)

normal_distribution[1, 1]
normal_distribution[:, 1] 
normal_distribution[::-1, 1]
normal_distribution[1, :]

normal_distribution[normal_distribution > 0] # 1d!!!
normal_distribution[np.random.randn(6) > 0] # 2d!!!
normal_distribution[:, np.random.randn(8) > 0] # 2d!!!

ids = np.arange(0, 6, 2)
normal_distribution[ids]

array([[ 1.11290819,  0.53678883,  0.95677494, -0.58315618,  0.22064085,
        -0.56952053, -0.00634408,  0.93711405],
       [ 0.80664412,  0.36942141, -0.54610433,  0.45318784,  0.67904037,
         0.04522392, -0.24210308,  1.12616577],
       [ 0.07480189, -0.35458132,  0.44053341,  0.82149288,  1.58153533,
        -0.50471208,  1.19977057, -0.25837263]])

In [8]:
# Operations with slices
normal_distribution = np.random.randn(6, 4)
print(normal_distribution)
normal_distribution[:, 1] = 10
print(normal_distribution)

[[-0.54237926  0.58529465  1.21931899 -2.13545739]
 [ 0.10121346  0.88875159 -0.39884148 -0.31101041]
 [-1.15442655 -1.81404531 -1.3498683  -1.82264535]
 [-0.07890263 -0.56771651  0.7838692   0.30915667]
 [-0.32849365 -0.53898557 -1.97604693 -0.10050085]
 [-0.60153071 -1.01670092 -0.57882985 -1.67501161]]
[[-0.54237926 10.          1.21931899 -2.13545739]
 [ 0.10121346 10.         -0.39884148 -0.31101041]
 [-1.15442655 10.         -1.3498683  -1.82264535]
 [-0.07890263 10.          0.7838692   0.30915667]
 [-0.32849365 10.         -1.97604693 -0.10050085]
 [-0.60153071 10.         -0.57882985 -1.67501161]]
